### PR TITLE
Fix Coverage

### PR DESCRIPTION
**Pull request by nkaralis**
Duplicate PR to test the communication with coveralls.

### CODE REVIEW

**Comment by nkaralis** [comment]
I was able to get a response from coveralls after sending the request from my machine. I am trying to figure out whether there is an issue with the workflow or with the authentication.

**Comment by bigerl** [comment]
image

Looks good now, right?

**Comment by bigerl** [comment]
I think this was not successful. If I understand @nkaralis correctly, he pointed out that commit https://github.com/rdf4cpp/rdf4cpp/pull/109/commits/894732eab606eb772bfb5d4d43b5b7ea15943794 reports coverage only because he submitted the results manually.

**Comment by liss-h** [comment]
My bad, misunderstood

**Pull request merged**
