### PR TITLE
use boost to convert case of string literals

### PR DESCRIPTION
**Pull request by mcb5637**
fix for #150

### CODE REVIEW

**Comment by bigerl** [comment]
The fetch-content workflow is failing with 
> Target "rdf4cpp" links to target "Boost::locale" but the target was not
  found. 

The respective package must be installed here: https://github.com/rdf4cpp/rdf4cpp/blob/develop/.github/workflows/reusable_fetch_content.yml#L43

For the CMake FetchContent retrieval we assume that the boost packages are installed on the system already.

**Review by bigerl — CHANGES_REQUESTED** [review]
Thank you for the PR. This review covers only the CI part. 

The fetch-content workflow is failing with 
> Target "rdf4cpp" links to target "Boost::locale" but the target was not
  found. 

The respective package must be installed here: https://github.com/rdf4cpp/rdf4cpp/blob/develop/.github/workflows/reusable_fetch_content.yml#L43

For the CMake FetchContent retrieval we assume that the boost packages are installed on the system already.

**Review by liss-h — CHANGES_REQUESTED** [review]
Hi :) impl looks fine, like mentioned in the meeting last week, my only concern is that the boost conversion function uses a locale, which, at least to me, does not make any sense. So I am currently not really convinced that this does the correct thing in all cases.

Reading the documentation for `boost::locale::to_upper` does not inspire that much confidence in me either. But there is probably nothing (at least nothing reasonable) that would convince me fully that this does what it is supposed to.

So:
- [x] So please add a comment in the functions that points to the part in the documentation that convinced you this does the correct thing
- [x] Also please add some more test cases that cover some common non-ascii characters in german or other languages
- [x] Additionally, please add a test case that ensures commas (in numbers) do not get converted. Realistically it would make absolutely no sense if this happens, just want to be sure.

**Review by bigerl — APPROVED** [review]

**Comment by bigerl** [comment]
(Approval is for the changes regarding the CI)

**Review by liss-h — APPROVED** [review]
Additions look good. One last thing: please add a comment under #150 explaining the progress and the thing(s) not working

**Comment by bigerl** [comment]
This came up today in my GitHub's explore repositories: https://github.com/uni-algo/uni-algo

Might be worth another look. 

Data for cases states to be up-to-date, i.e. 15.0.0: https://github.com/uni-algo/uni-algo/blob/main/include/uni_algo/impl/data/data_case.h

**Comment by bigerl** [comment]
#160 merged, closing this one

**Pull request closed without merging**
